import { Link } from "react-router-dom";

const Terms = () => {
  return (
    <div className="min-h-screen bg-[#F5F8FC] text-[#1a1a1a]">
      <header className="border-b border-slate-200/60 bg-white">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5">
          <Link to="/" className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#00B2E0]">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <rect x="3" y="3" width="7" height="7" rx="1" />
                <rect x="14" y="3" width="7" height="7" rx="1" />
                <rect x="3" y="14" width="7" height="7" rx="1" />
                <rect x="14" y="14" width="7" height="7" rx="1" />
              </svg>
            </div>
            <span className="text-lg font-black tracking-tight">Blueprint</span>
          </Link>
          <nav className="flex items-center gap-6 text-sm font-semibold text-slate-600">
            <Link to="/support" className="hover:text-[#00B2E0] transition-colors">Support</Link>
            <Link to="/privacy" className="hover:text-[#00B2E0] transition-colors">Privacy</Link>
            <Link to="/terms" className="text-[#00B2E0]">Terms</Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="mb-2 text-4xl font-black tracking-tight">Terms of Use</h1>
        <p className="mb-10 text-sm text-slate-400">Effective date: July 23, 2026</p>

        <div className="space-y-8 text-slate-700 leading-relaxed">
          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using Blueprint, you agree to these Terms of Use. If you do not
              agree, do not use the app.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">License to Use</h2>
            <p>
              Blueprint is provided under a personal, non-exclusive, non-transferable license. You may use
              the app for your personal fitness and health purposes. You may not reverse engineer, modify,
              redistribute, or resell the app or its content.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your Apple or Google account used to sign
              in. You must be at least 18 years old to use Blueprint. You agree to provide accurate profile
              information, as AI-generated plans depend on it.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Acceptable Use</h2>
            <ul className="space-y-2 text-sm">
              <li>Use the app only for lawful fitness and nutrition purposes</li>
              <li>Do not upload photos of other people without their consent</li>
              <li>Do not use the app to diagnose, treat, or cure any medical condition</li>
              <li>Do not attempt to abuse, overload, or disrupt the AI services</li>
              <li>Do not use the app for commercial fitness coaching or reselling</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">AI-Generated Content Disclaimer</h2>
            <p>
              Blueprint's training plans, physique analyses, food identification, and nutrition recommendations
              are generated by AI (Anthropic Claude) and are for informational purposes only. They are not
              medical advice, and AI may produce inaccurate or incomplete results. Always consult a qualified
              fitness professional, physician, or registered dietitian before starting any exercise or nutrition
              program. You assume all risk associated with following AI-generated recommendations.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Subscriptions</h2>
            <div className="space-y-3 text-sm">
              <p><strong>Blueprint Pro</strong> — $7.99/month with a 7-day free trial. Unlocks the full weekly training plan, exercise details, and progress tracking.</p>
              <p><strong>Nutrition Add-on</strong> — $7.99/month with a 3-day free trial. Unlocks AI meal planning, food photo scanning, barcode scanning, and full nutrition tracking.</p>
              <p>
                Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current
                billing period. You can manage or cancel subscriptions in your iPhone Settings → Apple ID →
                Subscriptions. Refunds are handled by Apple according to their refund policy.
              </p>
              <p>
                Free tier: onboarding, 1 baseline scan, and the first 3 training days are available without
                a subscription.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">User Content</h2>
            <p>
              You retain ownership of all photos, food logs, and workout data you create in Blueprint. Your
              physique photos and goal photos are stored on your device only. You are responsible for the
              content you upload and must have the right to do so.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Privacy</h2>
            <p>
              Our handling of your data is described in our
              <Link to="/privacy" className="text-[#00B2E0] font-semibold"> Privacy Policy</Link>. By using
              Blueprint, you consent to the data practices described there.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Service Availability</h2>
            <p>
              We strive to keep Blueprint available but do not guarantee uninterrupted access. AI features
              depend on third-party services (Anthropic) and may be unavailable during outages. We may
              update, modify, or discontinue features at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Disclaimer</h2>
            <p>
              Blueprint is provided "as is" without warranties of any kind. We do not guarantee that AI
              analysis will be accurate, complete, or suitable for your needs. Exercise carries inherent
              risk of injury. You are responsible for using proper form, appropriate weights, and seeking
              medical clearance before starting any fitness program.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Blueprint and its developers shall not be liable for
              any direct, indirect, incidental, special, or consequential damages arising from your use of
              the app, including but not limited to injury, data loss, or decisions made based on AI-generated
              recommendations.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Termination</h2>
            <p>
              You may stop using Blueprint at any time by deleting the app. We may terminate or restrict
              access for violations of these Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-[#1a1a1a]">Contact</h2>
            <p>
              For questions about these Terms, email
              <a href="mailto:support@blueprint.app" className="text-[#00B2E0] font-semibold"> support@blueprint.app</a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-slate-200/60 bg-white py-8">
        <div className="mx-auto max-w-4xl px-6 text-center text-sm text-slate-400">
          <p>&copy; 2026 Blueprint. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Terms;
